from pathlib import Path
import re

path = Path(r"E:\trip\france_trip_guide_2026.html")
text = path.read_text(encoding="utf-8")


def replace_article(day_id, new_html):
    global text
    pattern = rf'<article class="day" id="{day_id}">.*?</article>'
    text2, n = re.subn(pattern, new_html, text, count=1, flags=re.S)
    if n != 1:
        raise RuntimeError(f"{day_id}: {n} matches")
    text = text2

text = text.replace(
    '长途交通以出票信息为准；TER、ZOU、杭州—上海高铁在出发前再次确认具体班次。',
    '长途交通以出票信息为准；区域铁路、公交与机场交通在出发前再次确认具体班次。'
)

replace_article("d0928", r'''<article class="day" id="d0928"><div class="dayhead"><div><h3>9/28 周一 · 杭州 → 广州 → 阿姆斯特丹</h3><div class="sub">从杭州萧山机场出发，经广州转机，搭乘南航联程前往阿姆斯特丹。</div></div><div class="walk"><b>约 2–3 km</b>以机场转场为主 · ★☆☆☆☆</div></div>
  <div class="route-ribbon"><span>滨江</span><i class="arrow">→</i><span>HGH T4</span><i class="arrow">→</i><span>CZ3802</span><i class="arrow">→</i><span>CAN T2</span><i class="arrow">→</i><span>CZ307</span></div>
  <div class="timeline">
    <div class="step"><div class="time">17:30–18:20</div><h4>滨江家里 → 杭州萧山机场 T4</h4><img class="step-photo" src="images/steps/hangzhou.jpg" alt="杭州出发" loading="lazy"><p>直接网约车前往杭州萧山国际机场 T4，携带护照、申根签证、后续住宿与返程行程单。</p><div class="btnrow"><a class="btn light nav-now" href="https://www.google.com/maps/dir/?api=1&destination=Hangzhou%20Xiaoshan%20International%20Airport%20Terminal%204&travelmode=driving" target="_blank" rel="noopener">一键导航</a></div></div>
    <div class="step"><div class="time">18:20–20:45</div><h4>HGH T4 · 值机与托运行李</h4><img class="step-photo" src="images/steps/hgh-t4.jpg" alt="杭州萧山机场 T4" loading="lazy"><p>CZ3802 与 CZ307 为联程订单。值机时确认托运行李直挂 <b>AMS</b>；免费行李为 <b>1件8 kg手提 + 1件23 kg托运</b>。</p></div>
    <div class="step"><div class="time">21:35–23:50</div><h4>CZ3802 · HGH T4 → CAN T2</h4><img class="step-photo" src="images/steps/china-southern.jpg" alt="中国南方航空" loading="lazy"><p>21:35从杭州起飞，23:50抵达广州白云机场 T2；抵达后按国际转机指引前往下一程。</p></div>
    <div class="step"><div class="time">23:50–01:55</div><h4>广州白云 T2 · 国际转机</h4><img class="step-photo" src="images/steps/can-t2.jpg" alt="广州白云机场 T2" loading="lazy"><p>转机时间 <b>2小时05分</b>。确认单显示无需领取并重新托运行李；按现场 <b>International Transfer / 国际转机</b> 标识完成手续并前往 CZ307 登机口。</p></div>
  </div>
  </article>''')

replace_article("d0929", r'''<article class="day" id="d0929"><div class="dayhead"><div><h3>9/29 周二 · 阿姆斯特丹：国立博物馆、运河 → 巴黎</h3><div class="sub">上午抵达阿姆斯特丹，参观 Rijksmuseum 并乘运河游船，傍晚搭乘 Eurostar 前往巴黎。</div></div><div class="walk"><b>约 5–7 km</b>长途飞行后控制强度 · ★★★☆☆</div></div>
  <div class="route-ribbon"><span>AMS</span><i class="arrow">→</i><span>Amsterdam Centraal</span><i class="arrow">→</i><span>Rijksmuseum</span><i class="arrow">→</i><span>运河游船</span><i class="arrow">→</i><span>Eurostar 9476</span><i class="arrow">→</i><span>Paris Nord</span><i class="arrow">→</i><span>Bercy</span></div>
  <div class="timeline">
    <div class="step"><div class="time">01:55–08:00</div><h4>CZ307 · CAN T2 → Amsterdam Schiphol</h4><img class="step-photo" src="images/steps/china-southern.jpg" alt="CZ307 广州至阿姆斯特丹" loading="lazy"><p>01:55从广州起飞，08:00当地时间抵达阿姆斯特丹史基浦机场。</p></div>
    <div class="step"><div class="time">08:00–09:40</div><h4>Schiphol · 入境 + 取行李</h4><img class="step-photo" src="images/steps/schiphol.jpg" alt="Amsterdam Schiphol Airport" loading="lazy"><p>办理申根入境并领取托运行李。法国为本次行程主要目的地，可随身准备法国住宿、Eurostar 与后续行程证明。</p></div>
    <div class="step"><div class="time">09:40–10:20</div><h4>Schiphol → Amsterdam Centraal · 寄存行李</h4><img class="step-photo" src="images/steps/amsterdam-centraal.jpg" alt="Amsterdam Centraal" loading="lazy"><p>乘 NS 火车前往 <b>Amsterdam Centraal</b>，车程约15–20分钟。到站后使用车站行李柜寄存大件行李，再轻装前往博物馆区。</p><div class="btnrow"><a class="btn" href="https://www.ns.nl/en/travel/at-the-station/facilities/luggage-at-the-station" target="_blank">NS 行李柜</a><a class="btn light nav-now" href="https://www.google.com/maps/dir/?api=1&origin=Amsterdam%20Airport%20Schiphol&destination=Amsterdam%20Centraal&travelmode=transit" target="_blank" rel="noopener">一键导航</a></div></div>
    <div class="step"><div class="time">10:20–10:50</div><h4>Amsterdam Centraal → Rijksmuseum</h4><img class="step-photo" src="images/steps/amsterdam-centraal.jpg" alt="Amsterdam Centraal 前往 Rijksmuseum" loading="lazy"><p>按当天实时公交或电车导航前往 Museumplein，预留约10分钟在入口整理票券并入场。</p><div class="btnrow"><a class="btn light nav-now" href="https://www.google.com/maps/dir/?api=1&origin=Amsterdam%20Centraal&destination=Rijksmuseum%20Amsterdam&travelmode=transit" target="_blank" rel="noopener">一键导航</a></div></div>
    <div class="step"><div class="time">11:00–13:00</div><h4>Rijksmuseum · 国立博物馆</h4><img class="step-photo" src="images/steps/rijksmuseum.jpg" alt="Rijksmuseum" loading="lazy"><p><span class="badge check">预约 11:00</span> 重点参观 <b>Gallery of Honour、Vermeer、Rembrandt《The Night Watch》</b> 等核心馆藏，预留约2小时。</p><div class="btnrow"><a class="btn" href="https://www.rijksmuseum.nl/en/tickets" target="_blank">Rijksmuseum 官方票务</a><a class="btn light" href="https://www.google.com/maps/search/?api=1&query=Rijksmuseum%20Amsterdam" target="_blank">地图</a></div></div>
    <div class="step"><div class="time">13:00–13:40</div><h4>博物馆区 · 午餐</h4><img class="step-photo" src="images/food/croissant.jpg" alt="阿姆斯特丹午餐" loading="lazy"><p>在 Museumplein 周边选择简餐，13:40左右返回 Amsterdam Centraal 一带。</p></div>
    <div class="step"><div class="time">13:40–14:20</div><h4>Rijksmuseum → Amsterdam Centraal</h4><img class="step-photo" src="images/steps/amsterdam-centraal.jpg" alt="返回 Amsterdam Centraal" loading="lazy"><p>乘公交或电车返回中央站，步行前往中央站附近的运河游船码头。</p><div class="btnrow"><a class="btn light nav-now" href="https://www.google.com/maps/dir/?api=1&origin=Rijksmuseum%20Amsterdam&destination=Amsterdam%20Centraal&travelmode=transit" target="_blank" rel="noopener">一键导航</a></div></div>
    <div class="step"><div class="time">约14:30–15:30</div><h4>Amsterdam Canal Cruise · 运河游船</h4><img class="step-photo" src="images/steps/amsterdam-canal.webp" alt="阿姆斯特丹运河游船" loading="lazy"><p>选择 Amsterdam Centraal 附近码头的约1小时游船。若 CZ307 当天明显晚点，优先保留 Rijksmuseum，并取消这一项。</p><div class="btnrow"><a class="btn" href="https://www.iamsterdam.com/en/tickets/canal-cruise-ticket" target="_blank">I amsterdam 游船信息</a></div></div>
    <div class="step"><div class="time">15:30–16:20</div><h4>取行李 + 车站补给</h4><img class="step-photo" src="images/steps/amsterdam-centraal.jpg" alt="Amsterdam Centraal 行李寄存" loading="lazy"><p>回 Amsterdam Centraal 取行李，购买水和火车上需要的食物，并确认 Eurostar 站台信息。</p></div>
    <div class="step"><div class="time">16:20–17:10</div><h4>Eurostar 9476 · 候车与登车</h4><img class="step-photo" src="images/steps/eurostar-amsterdam.jpg" alt="Eurostar Amsterdam Centraal" loading="lazy"><p>车票要求最晚 <b>16:50</b> 到站。Standard，<b>6车64座</b>，PNR <b>MCMMDY</b>；行李为2件不超过75 cm的大件 + 1件小随身包，自行搬运。</p></div>
    <div class="step"><div class="time">17:10–20:40</div><h4>Eurostar 9476 · Amsterdam → Paris Nord</h4><img class="step-photo" src="images/steps/eurostar-amsterdam.jpg" alt="Eurostar 前往巴黎" loading="lazy"><p>17:10从 Amsterdam Centraal 出发，20:40抵达 <b>Paris Gare du Nord</b>。</p></div>
    <div class="step"><div class="time">20:40–21:35</div><h4>Paris Nord → The People – Paris Bercy</h4><img class="step-photo" src="images/steps/paris-metro.jpg" alt="巴黎地铁" loading="lazy"><p>按当晚实时导航乘地铁前往 Daumesnil 一带，再步行至 <b>28 Boulevard de Reuilly</b>。</p><div class="btnrow"><a class="btn light nav-now" href="https://www.google.com/maps/dir/?api=1&origin=Gare%20du%20Nord%20Paris&destination=The%20People%20Paris%20Bercy%2028%20Boulevard%20de%20Reuilly%20Paris&travelmode=transit" target="_blank" rel="noopener">一键导航</a></div></div>
    <div class="step"><div class="time">21:35–22:15</div><h4>入住 The People – Paris Bercy</h4><img class="step-photo" src="images/steps/people-bercy.webp" alt="The People Paris Bercy" loading="lazy"><p>9/29–9/30为单独一笔6人女生宿舍订单。办理入住时同时出示9/30–10/3的下一笔订单，询问能否连续使用同一床位。</p></div>
  </div>
  <iframe class="map" loading="lazy" src="https://www.google.com/maps?q=Rijksmuseum+Amsterdam&output=embed" title="阿姆斯特丹地图"></iframe></article>''')

replace_article("d0930", r'''<article class="day" id="d0930"><div class="dayhead"><div><h3>9/30 周三 · 蒙马特 → Opéra → 玛黑古着</h3><div class="sub">上午游览蒙马特与歌剧院一带，下午沿玛黑区逛古着店、Rue des Rosiers 和 Place des Vosges。</div></div><div class="walk"><b>约 9–11 km</b>步行强度 ★★★☆☆</div></div>
  <div class="route-ribbon"><span>Bercy</span><i class="arrow">→</i><span>Montmartre</span><i class="arrow">→</i><span>Opéra</span><i class="arrow">→</i><span>Galeries Lafayette</span><i class="arrow">→</i><span>Guerrisol</span><i class="arrow">→</i><span>Free'P'Star</span><i class="arrow">→</i><span>Rue des Rosiers</span><i class="arrow">→</i><span>Place des Vosges</span><i class="arrow">→</i><span>La Cadette</span></div>
  <div class="timeline">
    <div class="step"><div class="time">08:30–09:15</div><h4>早餐 + 住宿订单衔接</h4><img class="step-photo" src="images/steps/people-kitchen.jpg" alt="The People Paris Bercy 早餐" loading="lazy"><p>先向前台确认两笔连续订单能否保留同一床位；如需换床，10:30前办理退房并将行李寄存在前台。</p></div>
    <div class="step"><div class="time">09:15–09:45</div><h4>Daumesnil → Montmartre</h4><img class="step-photo" src="images/steps/paris-metro.jpg" alt="前往蒙马特" loading="lazy"><p>按实时导航乘地铁前往 Anvers / Abbesses 一带，从山下开始游览。</p><div class="btnrow"><a class="btn light nav-now" href="https://www.google.com/maps/dir/?api=1&destination=Sacr%C3%A9-C%C5%93ur%20Paris&travelmode=transit" target="_blank" rel="noopener">一键导航</a></div></div>
    <div class="step"><div class="time">09:45–11:45</div><h4>Montmartre → Sacré-Cœur</h4><img class="step-photo" src="images/sights/sacre.jpg" alt="巴黎圣心堂" loading="lazy"><p>游览蒙马特街区与圣心堂，在高处停留看巴黎城市景观。</p><div class="btnrow"><a class="btn light" href="https://www.google.com/maps/search/?api=1&query=Sacr%C3%A9-C%C5%93ur%20Paris" target="_blank">圣心堂地图</a></div></div>
    <div class="step"><div class="time">12:00–13:00</div><h4>蒙马特 · 午餐</h4><img class="step-photo" src="images/food/croissant.jpg" alt="巴黎简餐" loading="lazy"><p>在蒙马特或前往 Opéra 的路上选择面包店 / 简餐，13:00左右继续前往歌剧院一带。</p></div>
    <div class="step"><div class="time">13:15–13:40</div><h4>Palais Garnier · 巴黎歌剧院外观</h4><img class="step-photo" src="images/steps/opera.jpg" alt="Palais Garnier" loading="lazy"><p>游览歌剧院广场并看建筑外观，之后步行前往 Galeries Lafayette Haussmann。</p></div>
    <div class="step"><div class="time">13:40–14:20</div><h4>Galeries Lafayette · 穹顶与屋顶</h4><img class="step-photo" src="images/steps/galeries-rooftop.jpg" alt="Galeries Lafayette 屋顶" loading="lazy"><p>看老佛爷百货穹顶；屋顶当天开放时可顺路前往，官方露台免费且无需预约。</p><div class="btnrow"><a class="btn" href="https://haussmann.galerieslafayette.com/en/the-terrace-at-galeries-lafayette/" target="_blank">屋顶官方</a></div></div>
    <div class="step"><div class="time">14:20–14:45</div><h4>Haussmann → Guerrisol Sébastopol</h4><img class="step-photo" src="images/steps/paris-metro.jpg" alt="前往 Guerrisol" loading="lazy"><p>从 Chaussée d’Antin–La Fayette 一带乘 <span class="transit">M7</span> 至 Châtelet，再步行前往 <b>8 Boulevard de Sébastopol</b>。</p><div class="btnrow"><a class="btn light nav-now" href="https://www.google.com/maps/dir/?api=1&origin=Galeries%20Lafayette%20Haussmann%20Paris&destination=Guerrisol%208%20Boulevard%20de%20S%C3%A9bastopol%20Paris&travelmode=transit" target="_blank" rel="noopener">一键导航</a></div></div>
    <div class="step"><div class="time">14:45–15:20</div><h4>Guerrisol Sébastopol</h4><img class="step-photo" src="images/steps/guerrisol.jpg" alt="Guerrisol 巴黎古着店" loading="lazy"><p>低价二手衣物为主，适合快速翻找彩色上衣、印花裙、外套和配饰；普通基础款可减少停留时间。</p><div class="btnrow"><a class="btn" href="https://www.guerrisol.fr/magasins" target="_blank">Guerrisol 官方门店</a></div></div>
    <div class="step"><div class="time">15:20–16:20</div><h4>Free'P'Star · Rue de la Verrerie</h4><img class="step-photo" src="images/steps/freepstar.jpg" alt="Free'P'Star 古着店" loading="lazy"><p>步行进入玛黑区，前往 <b>52 Rue de la Verrerie</b>。店内以70s / rock 风格古着为主，并设有低价淘货区；同街另一家分店可视时间决定是否进入。</p><div class="btnrow"><a class="btn" href="https://parisjetaime.com/eng/shopping/free-p-star-p2318" target="_blank">Paris je t’aime</a><a class="btn light" href="https://www.google.com/maps/search/?api=1&query=Free%27P%27Star%2052%20Rue%20de%20la%20Verrerie%20Paris" target="_blank">地图</a></div></div>
    <div class="step"><div class="time">16:20–17:20</div><h4>Le Marais · Rue des Rosiers</h4><img class="step-photo" src="images/steps/rue-rosiers.webp" alt="Rue des Rosiers" loading="lazy"><p>从 Rue de la Verrerie 向东步行，经 Rue Sainte-Croix-de-la-Bretonnerie、Rue Vieille du Temple 和 <b>Rue des Rosiers</b>，继续游览玛黑街区。</p><div class="btnrow"><a class="btn light nav-now" href="https://www.google.com/maps/dir/?api=1&origin=Free%27P%27Star%2052%20Rue%20de%20la%20Verrerie%20Paris&destination=Place%20des%20Vosges%20Paris&waypoints=Rue%20des%20Rosiers%20Paris&travelmode=walking" target="_blank" rel="noopener">打开步行路线</a></div></div>
    <div class="step"><div class="time">17:20–17:40</div><h4>Place des Vosges</h4><img class="step-photo" src="images/steps/place-vosges.jpg" alt="Place des Vosges" loading="lazy"><p>在孚日广场短暂停留和休息，随后从 Bastille 一带前往12区。</p></div>
    <div class="step"><div class="time">17:40–18:00</div><h4>Place des Vosges → La Cadette</h4><img class="step-photo" src="images/steps/paris-metro.jpg" alt="前往 La Cadette" loading="lazy"><p>前往 Bastille，乘 <span class="transit">M1</span> 到 Reuilly–Diderot，再步行至 <b>8 Rue Riesener</b>。</p><div class="btnrow"><a class="btn light nav-now" href="https://www.google.com/maps/dir/?api=1&origin=Place%20des%20Vosges%20Paris&destination=La%20Cadette%208%20Rue%20Riesener%20Paris&travelmode=transit" target="_blank" rel="noopener">一键导航</a></div></div>
    <div class="step"><div class="time">18:00–18:45</div><h4>La Cadette · Friperie Atelier</h4><img class="step-photo" src="images/steps/vintage-shop.jpg" alt="巴黎古着店" loading="lazy"><p>La Petite Rockette 的公益型古着店，周三14:00–19:00营业；衣物、配饰和皮具以亲民价格出售。</p><div class="btnrow"><a class="btn" href="https://www.lapetiterockette.org/infos_pratiques/" target="_blank">La Cadette 官方</a></div></div>
    <div class="step"><div class="time">18:45–19:05</div><h4>La Cadette → The People Bercy</h4><img class="step-photo" src="images/steps/people-bercy.webp" alt="The People Paris Bercy" loading="lazy"><p>从 Rue Riesener 步行返回青旅，距离较近；将购买的衣物放回房间后再解决晚餐和补给。</p><div class="btnrow"><a class="btn light nav-now" href="https://www.google.com/maps/dir/?api=1&origin=La%20Cadette%208%20Rue%20Riesener%20Paris&destination=The%20People%20Paris%20Bercy%2028%20Boulevard%20de%20Reuilly%20Paris&travelmode=walking" target="_blank" rel="noopener">一键导航</a></div></div>
    <div class="step"><div class="time">19:05–20:15</div><h4>超市采购 + 晚餐</h4><img class="step-photo" src="images/grocery/hachis.jpg" alt="巴黎超市采购" loading="lazy"><p>在青旅附近补充10/1–10/3所需的早餐、酸奶、微波餐和火车零食，之后回青旅休息。</p></div>
  </div>
  <iframe class="map" loading="lazy" src="https://www.google.com/maps?q=Le+Marais+Paris&output=embed" title="玛黑区地图"></iframe></article>''')

replace_article("d1007", r'''<article class="day" id="d1007"><div class="dayhead"><div><h3>10/7 周三 · 尼斯 → 米兰：Duomo、Brera、Navigli</h3><div class="sub">早班火车经文蒂米利亚前往米兰，下午游览大教堂、Brera、Sforza 城堡和 Navigli。</div></div><div class="walk"><b>约 7–9 km</b>早起转场 + 市区步行 · ★★★★☆</div></div>
  <div class="route-ribbon"><span>SLO Nice</span><i class="arrow">→</i><span>Nice Ville</span><i class="arrow">→</i><span>Ventimiglia</span><i class="arrow">→</i><span>Milano Centrale</span><i class="arrow">→</i><span>Duomo</span><i class="arrow">→</i><span>Brera</span><i class="arrow">→</i><span>Castello Sforzesco</span><i class="arrow">→</i><span>Navigli</span></div>
  <div class="timeline">
    <div class="step"><div class="time">06:10–06:50</div><h4>SLO Nice · 退房 → Nice Ville</h4><img class="step-photo" src="images/steps/slo-nice.webp" alt="SLO Nice" loading="lazy"><p>前一晚准备早餐、水和车票；退房后步行前往 Nice Ville，06:50左右到站候车。</p><div class="btnrow"><a class="btn light nav-now" href="https://www.google.com/maps/dir/?api=1&origin=SLO%20Nice%2020%20Rue%20de%20Paris%20Nice&destination=Gare%20de%20Nice-Ville&travelmode=walking" target="_blank" rel="noopener">一键导航</a></div></div>
    <div class="step"><div class="time">07:23–08:21</div><h4>ZOU! 86007 · Nice Ville → Ventimiglia</h4><img class="step-photo" src="images/steps/ter-train.png" alt="ZOU 区域列车" loading="lazy"><p>已出票，2等座，票价 €10.60，订单参考号 <b>U21WR7</b>。</p></div>
    <div class="step"><div class="time">08:21–09:10</div><h4>Ventimiglia · 换乘</h4><img class="step-photo" src="images/steps/ter-train.png" alt="Ventimiglia 换乘" loading="lazy"><p>两段车票分开购买，换乘时间 <b>49分钟</b>。抵达后先确认 IC631 站台，再补水或购买简单早餐。</p></div>
    <div class="step"><div class="time">09:10–13:00</div><h4>Intercity 631 · Ventimiglia → Milano Centrale</h4><img class="step-photo" src="images/steps/milano-centrale.jpg" alt="Milano Centrale" loading="lazy"><p>2等 Classe Easy，<b>6车16A</b>，PNR <b>XE6CV5</b>；13:00抵达 Milano Centrale。</p></div>
    <div class="step"><div class="time">13:00–13:45</div><h4>Milano Centrale → Ostelzzz · 寄存行李</h4><img class="step-photo" src="images/steps/ostelzzz.jpg" alt="Ostelzzz Milano" loading="lazy"><p>前往 <b>Via Giorgio Jan 5A</b>。入住时间15:00以后，先在前台寄存行李，再轻装出发。</p><div class="btnrow"><a class="btn light nav-now" href="https://www.google.com/maps/dir/?api=1&origin=Milano%20Centrale&destination=Ostelzzz%20Milano%20Via%20Giorgio%20Jan%205A&travelmode=transit" target="_blank" rel="noopener">一键导航</a></div></div>
    <div class="step"><div class="time">13:45–14:10</div><h4>Lima → Duomo</h4><img class="step-photo" src="images/steps/duomo-milano.jpg" alt="米兰大教堂" loading="lazy"><p>步行到 Lima；乘 <span class="transit">M1</span> 直达 <b>Duomo</b>，无需换乘。</p></div>
    <div class="step"><div class="time">14:10–15:30</div><h4>Duomo di Milano · 米兰大教堂</h4><img class="step-photo" src="images/steps/duomo-milano.jpg" alt="Duomo di Milano" loading="lazy"><p>先在 Piazza del Duomo 欣赏完整正立面和尖塔群，再进入教堂内部参观。若购买屋顶票，在本次参观中一并完成，不另行返回。</p><div class="btnrow"><a class="btn" href="https://www.duomomilano.it/en/" target="_blank">Duomo 官方</a><a class="btn light" href="https://www.google.com/maps/search/?api=1&query=Duomo%20di%20Milano" target="_blank">地图</a></div></div>
    <div class="step"><div class="time">15:30–15:55</div><h4>Galleria Vittorio Emanuele II</h4><img class="step-photo" src="images/steps/galleria-milano.jpg" alt="Galleria Vittorio Emanuele II" loading="lazy"><p>从 Duomo 广场直接进入拱廊，游览玻璃穹顶和内部空间，并从北侧前往 La Scala。</p></div>
    <div class="step"><div class="time">15:55–16:15</div><h4>Teatro alla Scala · 外观</h4><img class="step-photo" src="images/steps/scala-milano.jpg" alt="Teatro alla Scala" loading="lazy"><p>游览 Piazza della Scala 和剧院外观，不安排馆内参观。</p></div>
    <div class="step"><div class="time">16:15–17:20</div><h4>Brera 街区</h4><img class="step-photo" src="images/steps/brera.jpg" alt="Brera 米兰" loading="lazy"><p>步行游览 Brera 小街、书店和咖啡馆，以街区氛围为主，不安排 Pinacoteca di Brera 馆内参观。</p></div>
    <div class="step"><div class="time">17:20–18:15</div><h4>Castello Sforzesco</h4><img class="step-photo" src="images/steps/sforza.jpg" alt="Castello Sforzesco" loading="lazy"><p>从 Brera 步行前往 Sforza 城堡，参观外观和开放庭院。</p><div class="btnrow"><a class="btn light" href="https://www.google.com/maps/search/?api=1&query=Castello%20Sforzesco%20Milano" target="_blank">地图</a></div></div>
    <div class="step"><div class="time">18:15–18:45</div><h4>Lanza → Porta Genova</h4><img class="step-photo" src="images/steps/paris-metro.jpg" alt="米兰地铁" loading="lazy"><p>走到 Lanza；乘 <span class="transit">M2</span> 前往 Porta Genova，再步行至 Navigli / Darsena。</p></div>
    <div class="step"><div class="time">18:45–20:45</div><h4>Navigli / Darsena · 晚餐</h4><img class="step-photo" src="images/steps/navigli.jpg" alt="Navigli 米兰运河" loading="lazy"><p>沿运河区散步并用晚餐，可在意面、risotto、cotoletta 或 aperitivo 正餐中现场选择。</p><div class="btnrow"><a class="btn light" href="https://www.google.com/maps/search/?api=1&query=Navigli%20Milano" target="_blank">地图</a></div></div>
    <div class="step"><div class="time">约21:15</div><h4>返回 Ostelzzz · 入住</h4><img class="step-photo" src="images/steps/ostelzzz.jpg" alt="Ostelzzz Milano" loading="lazy"><p>返回住宿办理入住，整理第二天去 Malpensa 机场所需的护照、机票和行李。</p></div>
  </div>
  <iframe class="map" loading="lazy" src="https://www.google.com/maps?q=Duomo+di+Milano&output=embed" title="米兰地图"></iframe></article>''')

replace_article("d1008", r'''<article class="day" id="d1008"><div class="dayhead"><div><h3>10/8 周四 · 米兰 → 巴库 → 阿斯塔纳</h3><div class="sub">上午从米兰前往马尔彭萨机场，经巴库转机，次日凌晨抵达阿斯塔纳。</div></div><div class="walk"><b>约 2–3 km</b>以机场转场为主 · ★☆☆☆☆</div></div>
  <div class="route-ribbon"><span>Ostelzzz</span><i class="arrow">→</i><span>Milano Centrale</span><i class="arrow">→</i><span>MXP T1</span><i class="arrow">→</i><span>J2036</span><i class="arrow">→</i><span>GYD T1</span><i class="arrow">→</i><span>J28049</span><i class="arrow">→</i><span>NQZ T1</span></div>
  <div class="timeline">
    <div class="step"><div class="time">06:45–07:20</div><h4>起床 + 退房</h4><img class="step-photo" src="images/steps/ostelzzz.jpg" alt="Ostelzzz Milano" loading="lazy"><p>订单不含早餐，可提前准备面包、酸奶或在前往车站途中购买简餐。</p></div>
    <div class="step"><div class="time">07:20–08:50</div><h4>Milano Centrale → Malpensa T1</h4><img class="step-photo" src="images/steps/malpensa-express.jpg" alt="Malpensa Express" loading="lazy"><p>前往 Milano Centrale，乘 <b>Malpensa Express</b> 至 MXP T1。当前全程约51分钟，具体10/8班次出发前确认。</p><div class="btnrow"><a class="btn" href="https://www.malpensaexpress.it/en/lines-and-timetable/most-searched-lines/milano-centrale-malpensa-aeroporto-t1-route/" target="_blank">Malpensa Express</a></div></div>
    <div class="step"><div class="time">08:50–10:45</div><h4>MXP T1 · 值机与托运行李</h4><img class="step-photo" src="images/steps/milano-centrale.jpg" alt="米兰返程准备" loading="lazy"><p>办理阿塞拜疆航空值机。免费行李为 <b>1件10 kg手提 + 1件23 kg托运</b>；同时确认托运行李在 NQZ 是否需要提取并重新托运。</p></div>
    <div class="step"><div class="time">11:25–18:05</div><h4>J2036 · MXP T1 → GYD T1</h4><img class="step-photo" src="images/steps/azerbaijan-airlines.jpg" alt="Azerbaijan Airlines" loading="lazy"><p>11:25从米兰起飞，18:05抵达巴库盖达尔·阿利耶夫国际机场 T1。</p></div>
    <div class="step"><div class="time">18:05–22:00</div><h4>巴库 GYD T1 · 转机</h4><img class="step-photo" src="images/steps/azerbaijan-airlines.jpg" alt="巴库转机" loading="lazy"><p>转机时间 <b>3小时55分</b>。按 International Transfer 指引前往下一程，不离开机场安排市区行程。</p></div>
    <div class="step"><div class="time">22:00–02:00</div><h4>J28049 · GYD T1 → NQZ T1</h4><img class="step-photo" src="images/steps/azerbaijan-airlines.jpg" alt="巴库至阿斯塔纳" loading="lazy"><p>22:00从巴库起飞，10/9凌晨02:00抵达阿斯塔纳 NQZ T1。</p></div>
  </div></article>''')

replace_article("d1009", r'''<article class="day" id="d1009"><div class="dayhead"><div><h3>10/9 周五 · 阿斯塔纳：大清真寺、Bayterek → 乌鲁木齐</h3><div class="sub">凌晨抵达后先在机场休息，白天游览阿斯塔纳核心地标，晚上返回机场搭乘航班前往乌鲁木齐。</div></div><div class="walk"><b>约 5–7 km</b>景点之间以打车为主 · ★★★☆☆</div></div>
  <div class="route-ribbon"><span>NQZ</span><i class="arrow">→</i><span>Astana Grand Mosque</span><i class="arrow">→</i><span>National Museum</span><i class="arrow">→</i><span>Bayterek</span><i class="arrow">→</i><span>Nurzhol</span><i class="arrow">→</i><span>Khan Shatyr</span><i class="arrow">→</i><span>NQZ</span></div>
  <div class="timeline">
    <div class="step"><div class="time">02:00–03:15</div><h4>NQZ T1 · 入境 + 行李确认</h4><img class="step-photo" src="images/steps/nqz-airport.jpg" alt="Astana NQZ Airport" loading="lazy"><p>办理哈萨克斯坦入境，并根据行李牌确认托运行李状态。订单提示阿斯塔纳段<b>可能需要领取并重新托运行李</b>；如行李只挂到 NQZ，先领取行李。</p></div>
    <div class="step"><div class="time">03:15–06:30</div><h4>NQZ T1 · 机场休息</h4><img class="step-photo" src="images/steps/nqz-airport.jpg" alt="阿斯塔纳机场" loading="lazy"><p>凌晨留在机场公共区域休息，护照、手机和银行卡贴身保管；天亮后再进入市区。</p></div>
    <div class="step"><div class="time">06:30–07:00</div><h4>寄存行李</h4><img class="step-photo" src="images/steps/nqz-airport.jpg" alt="阿斯塔纳机场行李寄存" loading="lazy"><p>如已领取大件行李，使用机场行李寄存服务后轻装出发；若行李已直挂 URC，则直接整理随身物品。</p></div>
    <div class="step"><div class="time">07:00–07:40</div><h4>早餐 + 前往 Astana Grand Mosque</h4><img class="step-photo" src="images/food/croissant.jpg" alt="阿斯塔纳早餐" loading="lazy"><p>在机场简单早餐后乘正规出租车 / 网约车前往 <b>Astana Grand Mosque</b>。</p></div>
    <div class="step"><div class="time">07:45–09:15</div><h4>Astana Grand Mosque</h4><img class="step-photo" src="images/steps/astana-mosque.jpg" alt="Astana Grand Mosque" loading="lazy"><p>参观蓝色穹顶大清真寺的外观和内部空间。女性准备可覆盖头发的围巾，衣着遮肩遮膝，入内脱鞋。10/9为周五，安排在早晨可避开中午聚礼时段。</p><div class="btnrow"><a class="btn light" href="https://visitastana.kz/en/about-city/what-to-see/mechet-v-g-nur-sultan/" target="_blank">Visit Astana</a><a class="btn light" href="https://www.google.com/maps/search/?api=1&query=Astana%20Grand%20Mosque" target="_blank">地图</a></div></div>
    <div class="step"><div class="time">09:15–10:00</div><h4>Grand Mosque → National Museum</h4><img class="step-photo" src="images/steps/kazakhstan-museum.jpg" alt="National Museum of Kazakhstan" loading="lazy"><p>乘车前往 National Museum；如提前抵达，可在 Independence Square 一带短暂停留。</p></div>
    <div class="step"><div class="time">10:00–11:30</div><h4>National Museum of Kazakhstan</h4><img class="step-photo" src="images/steps/kazakhstan-museum.jpg" alt="哈萨克斯坦国家博物馆" loading="lazy"><p>重点参观 Golden Man、古代游牧文明、哈萨克民族文化和阿斯塔纳城市发展相关展厅，预留约1.5小时。</p><div class="btnrow"><a class="btn" href="https://nmrk.kz/en/" target="_blank">国家博物馆官方</a></div></div>
    <div class="step"><div class="time">11:30–12:30</div><h4>午餐 + 前往 Bayterek</h4><img class="step-photo" src="images/steps/baiterek.jpg" alt="Bayterek" loading="lazy"><p>在新城核心区附近解决午餐，之后前往 Bayterek。</p></div>
    <div class="step"><div class="time">12:30–15:10</div><h4>Bayterek → Nurzhol Boulevard → Ak Orda</h4><img class="step-photo" src="images/steps/baiterek.jpg" alt="Bayterek 阿斯塔纳" loading="lazy"><p>游览 Bayterek，并沿 Nurzhol Boulevard 步行看新城建筑；继续至 Ak Orda 一带看总统府外观。</p><div class="btnrow"><a class="btn light" href="https://a-vm.kz/en/objects/bayterek/" target="_blank">Bayterek 官方信息</a></div></div>
    <div class="step"><div class="time">15:20–17:15</div><h4>Khan Shatyr</h4><img class="step-photo" src="images/steps/khan-shatyr.jpg" alt="Khan Shatyr" loading="lazy"><p>参观 Norman Foster 设计的巨型帐篷建筑，并在室内休息。体力不足时可缩短这一站。</p><div class="btnrow"><a class="btn light" href="https://visitastana.kz/en/about-city/what-to-see/khan-shatyr-sec/" target="_blank">Visit Astana</a></div></div>
    <div class="step"><div class="time">17:15–18:00</div><h4>Khan Shatyr → NQZ</h4><img class="step-photo" src="images/steps/nqz-airport.jpg" alt="返回阿斯塔纳机场" loading="lazy"><p>乘车返回 NQZ T1，为晚间国际航班预留充足时间。</p></div>
    <div class="step"><div class="time">18:00–19:00</div><h4>取行李 + 办理值机</h4><img class="step-photo" src="images/steps/nqz-airport.jpg" alt="NQZ T1" loading="lazy"><p>如早晨寄存了行李，先领取行李；随后确认 FS7961 值机柜台并办理20 kg托运行李。</p></div>
    <div class="step"><div class="time">19:00–22:00</div><h4>NQZ T1 · 边检 + 晚餐 + 候机</h4><img class="step-photo" src="images/steps/nqz-airport.jpg" alt="阿斯塔纳机场候机" loading="lazy"><p>完成出境与安检后在候机区用晚餐，提前查看 FS7961 登机口。</p></div>
    <div class="step"><div class="time">22:30–03:55</div><h4>FS7961 · NQZ T1 → URC T4</h4><img class="step-photo" src="images/steps/flyarystan.webp" alt="FlyArystan" loading="lazy"><p>飞狮航空，订单显示1件20 kg托运行李；10/10凌晨03:55抵达乌鲁木齐天山国际机场 T4。</p></div>
  </div>
  <iframe class="map" loading="lazy" src="https://www.google.com/maps?q=Astana+Grand+Mosque&output=embed" title="阿斯塔纳地图"></iframe></article>''')

replace_article("d1010", r'''<article class="day" id="d1010"><div class="dayhead"><div><h3>10/10 周六 · 乌鲁木齐抵达</h3><div class="sub">凌晨抵达乌鲁木齐，完成入境和取行李后结束本次行程。</div></div><div class="walk"><b>抵达日</b>步行强度 ★☆☆☆☆</div></div>
  <div class="timeline">
    <div class="step"><div class="time">03:55–05:30</div><h4>乌鲁木齐天山国际机场 T4 · 入境 + 取行李</h4><img class="step-photo" src="images/steps/urumqi-t4.jpg" alt="乌鲁木齐天山国际机场 T4" loading="lazy"><p>办理中国入境、海关和取行李手续，之后按实际接送或住宿安排离开机场。</p></div>
  </div></article>''')

# Rijksmuseum checklist: only the booking target, not unrelated checkout times.
text = text.replace('<b>Rijksmuseum 9/29：</b>目标10:30左右入场，优先级最高。', '<b>Rijksmuseum 9/29：</b>预约11:00入场。')

path.write_text(text, encoding="utf-8")
print("updated", path)
